#!/usr/bin/env bash
#display a numbers with display bad lucj numbers from china&japan&italy
i=1
while ((i <= 20))
do
	echo $i
	if ((i == 4))
	then
		echo bad luck from China
	elif ((i == 9))
	then
		echo bad luck from Japan
	elif ((i == 17))
	then
		echo bad luck from Italy
	fi
	((i++))
done
