#!/usr/bin/env bash
# hours and min
hours=0
minutes=0
echo Hour: 0
while ((hours <= 12))
do
((minutes++))
if ((minutes % 60 == 0))
then
    ((hours++))
     minutes=1
    if ((hours <= 12))
    then
        echo Hour: $hours
    else
        break
    fi
fi
echo $minutes
done